# Generated by Django 5.0.2 on 2024-02-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0002_alter_organization_createdby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswers',
            name='status',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='status',
        ),
    ]
