# Generated by Django 5.0.2 on 2024-03-08 05:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('enrollmentDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('enroll', 'Enroll'), ('start', 'Start'), ('complete', 'Complete')], max_length=50)),
                ('completingDate', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('timeTaken', models.IntegerField(default=0)),
                ('correctAnswer', models.IntegerField(default=0)),
                ('incorrectAnswer', models.IntegerField(default=0)),
                ('pendingAnswer', models.IntegerField(default=0)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_createdBy', to=settings.AUTH_USER_MODEL)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Quiz_Api.quiz')),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updatedBy', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
