# Generated by Django 5.0.2 on 2024-03-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0003_quizenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizenrollment',
            name='enrollmentDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
