# Generated by Django 5.0.2 on 2024-03-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0004_alter_quizenrollment_enrollmentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='totalQuestions',
        ),
    ]
