# Generated by Django 5.0.2 on 2024-02-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0004_alter_organization_isactive_alter_quiz_isactive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswers',
            name='isVerified',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='isVerified',
        ),
    ]
