# Generated by Django 5.0.2 on 2024-03-19 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0005_remove_quiz_totalquestions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestions',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=100),
        ),
        migrations.CreateModel(
            name='QuizPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('answerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_plays', to='Quiz_Api.quizoptions')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_createdBy', to=settings.AUTH_USER_MODEL)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_plays', to='Quiz_Api.quizquestions')),
                ('quizId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_plays', to='Quiz_Api.quiz')),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updatedBy', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
