# Generated by Django 5.0.2 on 2024-03-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0005_remove_quizanswers_isverified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswers',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
