# Generated by Django 5.0.2 on 2024-03-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0006_alter_quizquestions_level_quizplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizenrollment',
            name='status',
            field=models.CharField(choices=[('enroll', 'Enroll'), ('start', 'Start'), ('playing', 'Playing'), ('complete', 'Complete')], max_length=50),
        ),
    ]
