# Generated by Django 5.0.2 on 2024-03-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0006_quizanswers_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='tittle',
            new_name='title',
        ),
    ]
