# Generated by Django 5.0.2 on 2024-03-04 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0007_rename_tittle_quiz_title'),
        ('User', '0003_alter_user_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('option', models.TextField()),
                ('correctOption', models.BooleanField(default=False)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_createdBy', to='User.user')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Quiz_Api.quizquestions')),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updatedBy', to='User.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='QuizAnswers',
        ),
    ]
