# Generated by Django 5.0.2 on 2024-03-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0007_alter_quizenrollment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizenrollment',
            old_name='completingDate',
            new_name='playedDate',
        ),
    ]
