# Generated by Django 5.0.2 on 2024-03-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0008_quizoptions_delete_quizanswers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='organization',
            new_name='organization_id',
        ),
    ]
