# Generated by Django 5.0.2 on 2024-04-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0008_rename_completingdate_quizenrollment_playeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='eachCorrectQuestionPoint',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='eachIncorrectQuestionPoint',
            field=models.IntegerField(default=0),
        ),
    ]
