# Generated by Django 5.0.2 on 2024-04-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0009_quiz_eachcorrectquestionpoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='eachCorrectQuestionPoint',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='eachIncorrectQuestionPoint',
        ),
    ]
