# Generated by Django 5.0.2 on 2024-04-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0010_remove_quiz_eachcorrectquestionpoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizenrollment',
            name='score',
        ),
    ]
