# Generated by Django 5.0.2 on 2024-04-10 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0012_quiz_quiz_api_qu_startda_7670ac_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizenrollment',
            index=models.Index(fields=['quiz_id', 'user_id', 'status'], name='Quiz_Api_qu_quiz_id_882332_idx'),
        ),
    ]
