# Generated by Django 5.0.2 on 2024-04-11 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Api', '0014_remove_quiz_quiz_api_qu_startda_7670ac_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizoptions',
            index=models.Index(fields=['question_id', 'correctOption', 'isActive'], name='Quiz_Api_qu_questio_c7eecd_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestions',
            index=models.Index(fields=['quiz_id', 'isActive'], name='Quiz_Api_qu_quiz_id_c9ab72_idx'),
        ),
    ]
